### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by oshliaer** [classroomtechtools/chat-adv-service#1]
## Issue

I can't get any resource expect spaces list.

Below is an example and my current log.

## Test log

	  9:51:53 AM	Notice	Execution started
	  9:51:53 AM	Info	TAP version GasTap v0.2.0(BUGGY)
	  9:51:53 AM	Info	ok 1 - OK # PASS - spacesList
	  9:51:53 AM	Info	ok 2 - OK # PASS - getTestedSpace_
	  9:51:53 AM	Info	not ok 3 - returns 'undefined' # FAIL - membersList
	  9:51:54 AM	Info	{ error: 
	     { status: 500,
	       message: 'Unexpected token < in JSON at position 0',
	       charset: 'charset=utf-8',
	       mime: 'text/html' },
	    text: '<h1>Internal Server Error</h1>\n<h2>Error 500</h2>\n' }
	  9:51:54 AM	Info	not ok 4 - returns '{
	   "error": {
	    "status": 500,
	    "message": "Unexpected token < in JSON at position 0",
	    "charset": "charset=utf-8",
	    "mime": "text/html"
	   },
	   "text": "<h1>Internal Server Error</h1>\n<h2>Error 500</h2>\n"
	  }' # FAIL - message
	  9:51:54 AM	Notice	Execution completed

## Sample

https://script.google.com/d/10OGSJzSkLSU5UHhge56r3Ay3KMkAGiraxsiGuzbC8g9G8_NrZ1o4BfeN/edit?usp=sharing

**Comment by brainysmurf** [comment]
It must be an incorrect request object to get a 500 error response from the endpoint like that. If you can give my account edit access I'll put the library into dev mode and debug it that way.

**Comment by oshliaer** [comment]
@brainysmurf 

- https://script.google.com/d/10OGSJzSkLSU5UHhge56r3Ay3KMkAGiraxsiGuzbC8g9G8_NrZ1o4BfeN/edit?usp=sharing can be edited by everyone now
- I don't use a spesific chats, bots, or spaces

**Comment by brainysmurf** [comment]
@contributorpw 
Edit access is of no use anyway, can't run it outside the domain. But I've recreated it on my end. Has to do with how the request is being built.

**Comment by brainysmurf** [comment]
That was a doozy. The discovery document for that api gives an unexpected `uri`. Works for me now.

**Comment by brainysmurf** [comment]
@contributorpw can you confirm?

**Comment by oshliaer** [comment]
Hmmm... Not yet for me. I'll try to build the lib for myself and check what happens with the uri.

**Comment by brainysmurf** [comment]
Sorry. I didn’t realise this but I had to bump the ChatService lib version because I bumped the dependency library Endpoints.

Please bump ChatService to version 4 (you might have to refresh if the window was open). Should definitely work now.

**Comment by brainysmurf** [comment]
@contributorpw

**Comment by oshliaer** [comment]
@brainysmurf it works fine! Thank you!

>
