### ISSUE TITLE
Message cannot be empty

### ISSUE THREAD

**Issue by oshliaer** [classroomtechtools/chat-adv-service#2]
I have a simple function. There is its signature 

```js
function sendMessage_(service, space, text) {
  const name = space.name;
  const message = service.Messages.create(name, text);
  return message;
}
```

Other `service`'s methods behave fine on other calls for example `service.Members.list()` or `service.Spaces.list()` but `service.Messages.create` returns

```json
{
 "error": {
  "code": 400,
  "message": "Message cannot be empty.",
  "status": "INVALID_ARGUMENT"
 }
}
```

For testing you can copy the [project](https://script.google.com/d/10OGSJzSkLSU5UHhge56r3Ay3KMkAGiraxsiGuzbC8g9G8_NrZ1o4BfeN/edit?usp=sharing) and replace `SERVICE_ACCOUNT_KEY_FILE_ID` with your service account json file on Drive.

**Comment by brainysmurf** [comment]
Ha. I made a breaking change with Endpoints, but fixed now. I also found the same error with update messages. 

Bump the version and confim. Thanks for testing it's really useful.

**Comment by oshliaer** [comment]
v5 is working! Thank you!
